# Generated by Django 5.2.4 on 2025-07-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslot',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
