# Generated by Django 5.2.4 on 2025-07-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_remove_booking_vehicle_number_booking_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='floor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='number',
            field=models.IntegerField(),
        ),
    ]
