# Generated by Django 5.2.4 on 2025-07-09 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_parkingslot_floor_alter_parkingslot_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='slot_type',
            field=models.CharField(choices=[('REG', 'Regular'), ('EV', 'Electric Vehicle'), ('HC', 'Accessible')], default='REG', max_length=3),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='parking.parkingslot'),
        ),
    ]
