# Generated by Django 5.2.4 on 2025-07-09 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_parkingslot_slot_type_alter_booking_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingslot',
            name='slot_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingslot'),
        ),
    ]
