# Generated by Django 5.2.4 on 2025-07-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_remove_parkingslot_slot_type_booking_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='duration_hours',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='parking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='is_ev_charging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='is_handicap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='section',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='floor',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='parkingslot',
            unique_together={('floor', 'section', 'number')},
        ),
    ]
