# Generated by Django 5.2.4 on 2025-07-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_alter_parkingslot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='vehicle_number',
            field=models.CharField(max_length=20),
        ),
    ]
