# Generated by Django 5.2.4 on 2025-07-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_alter_booking_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='parking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
