# Generated by Django 5.2.4 on 2025-07-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_alter_booking_parking_date_alter_booking_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslot',
            name='floor',
            field=models.IntegerField(),
        ),
    ]
