# Generated by Django 5.2.4 on 2025-07-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0012_alter_parkingslot_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='floor',
            field=models.IntegerField(default=1),
        ),
    ]
