# Generated by Django 5.2.4 on 2025-07-16 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0014_remove_parkingslot_is_active_booking_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingslot',
            name='is_available',
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='active_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_slot', to='parking.booking'),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied')], default='AVAILABLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_bookings', to='parking.parkingslot'),
        ),
    ]
