# Generated by Django 5.2.4 on 2025-07-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0015_remove_parkingslot_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration_hours',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
    ]
